name: attraversiamo
favicon: null
layout_spectrum: 0.952092110645026
typography_spectrum: 0.527196949115023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.014319359790533781
  lightness: 0.7776146561373025
  saturation: 0.9083915257360786
  rhythmicContrast: 0.1993013012688607
purpose: []
